keys:
  - &admin_netali F72925946F580B058FB3F2719C55E636426B40A9
  - &admin_schlagma age1ncc0ukuqyeq8uzcvy2x0cymykrmnhzymgk22kvt7dvz99prjsysqjxgz9g
  - &srv_automatix age16ev6z7n6rcruusa98dw9gxyhyh228hsjp4d4f9su4sg3w9fsmymqqv99jt
  - &srv_grautvornix age1570w8z3cdn9ygjjupcyxjjn77g8d4me9s9na3uram5039kljsp3q4jrw0m
  - &srv_gutemine age1njs27c6tx64s8g5uu9jufenutagya8x2f4pnynjcgxzw8yx9sufs68epya
  - &srv_idefix age19e88slxz2qd2e6cspvpf85hv5lygrefrwtdn2vsrpqqvxekydaksetppys
  - &srv_majestix age1g6ygkqrtaz4jcjalndjvmepraf3sl0sr9e9zdth4x6frggfuhp9savtdls
  - &srv_miraculix age1hasnmsyqpyy790m48crw7q9lnvuswldy7znfyp9zsey4e8gm0gdqp8l6a2
  - &srv_obelix age15w5svtdpkvhskpce8xmthuwva3qcztw8nt48fkpq974r6dywfgcqm9s53h
  - &srv_obelus age1jx4wk4x6dexkw97exr2e2q2sdue68k970dcr543j98t6yc2mfa2qyev4pu
  - &srv_troubadix age1k0njnn7z8l3j600hhaux5fu0hy2gulp9kj4crauvsxzswt0pcddsu8pcl4
  - &srv_verliernix age1z0uzlmz2gpcqaw42jmr3xremvdpgasz4mwy273pwv77hrfxzr36s8cp2fq

creation_rules:
  - path_regex: hosts/server/automatix/secrets.yaml$
    key_groups:
      - age:
        - *srv_automatix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/grautvornix/secrets.yaml$
    key_groups:
      - age:
        - *srv_grautvornix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/gutemine/secrets.yaml$
    key_groups:
      - age:
        - *srv_gutemine
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/idefix/secrets.yaml$
    key_groups:
      - age:
        - *srv_idefix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/majestix/secrets.yaml$
    key_groups:
      - age:
        - *srv_majestix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/miraculix/secrets.yaml$
    key_groups:
      - age:
        - *srv_miraculix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/obelix/secrets.yaml$
    key_groups:
      - age:
        - *srv_obelix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/obelus/secrets.yaml$
    key_groups:
      - age:
        - *srv_obelus
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/troubadix/secrets.yaml$
    key_groups:
      - age:
        - *srv_troubadix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/verliernix/secrets.yaml$
    key_groups:
      - age:
        - *srv_verliernix
        - *admin_schlagma
        pgp:
        - *admin_netali
