keys:
  - &admin_netali F72925946F580B058FB3F2719C55E636426B40A9
  - &admin_schlagma age1ncc0ukuqyeq8uzcvy2x0cymykrmnhzymgk22kvt7dvz99prjsysqjxgz9g
  - &srv_automatix age1ss4mpym5gkgzqmjht0unpggjxz4w392n94afx4zglw27yj8ny9nq9rxx88
  - &srv_grautvornix age1570w8z3cdn9ygjjupcyxjjn77g8d4me9s9na3uram5039kljsp3q4jrw0m
  - &srv_gutemine age1jrdgsnxl0jqzdu7nk20ey97kehkcy57m6c7ww5au3nrw6vwyk9xq87jxgk
  - &srv_majestix age1es4y3s8sh0c67u3zsj72cvvfwcnx9ty7482w22dj8ajvngnatdtqx0gfdt
  - &srv_miraculix age1j78d0nj0jr7xk5mmgwcepjm7zrj0nun9t8meht3qrq5ywqqqudhs6syp5v
  - &srv_moralelastix age13f3yj47xps66xya6ksc7wzq63epn5avch996wuuscmqmhh7lefrselzepy
  - &srv_obelix age1hcnc4xp69rwh8dhcvgdrykd45pm9qy6u7cvmda2nrkp934z38gashg8vr8
  - &srv_troubadix age1k0njnn7z8l3j600hhaux5fu0hy2gulp9kj4crauvsxzswt0pcddsu8pcl4
  - &srv_verliernix age1z0uzlmz2gpcqaw42jmr3xremvdpgasz4mwy273pwv77hrfxzr36s8cp2fq

creation_rules:
  - path_regex: hosts/server/automatix/secrets.yaml$
    key_groups:
      - age:
        - *srv_automatix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/grautvornix/secrets.yaml$
    key_groups:
      - age:
        - *srv_grautvornix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/gutemine/secrets.yaml$
    key_groups:
      - age:
        - *srv_gutemine
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/majestix/secrets.yaml$
    key_groups:
      - age:
        - *srv_majestix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/miraculix/secrets.yaml$
    key_groups:
      - age:
        - *srv_miraculix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/moralelastix/secrets.yaml$
    key_groups:
      - age:
        - *srv_moralelastix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/obelix/secrets.yaml$
    key_groups:
      - age:
        - *srv_obelix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/troubadix/secrets.yaml$
    key_groups:
      - age:
        - *srv_troubadix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/server/verliernix/secrets.yaml$
    key_groups:
      - age:
        - *srv_verliernix
        - *admin_schlagma
        pgp:
        - *admin_netali

