keys:
  - &admin_netali age1r72zngdkax447se4a357n78huc86veuddjvkd4zumgn787q7vcuqwlnmq7
  - &admin_schlagma age1ncc0ukuqyeq8uzcvy2x0cymykrmnhzymgk22kvt7dvz99prjsysqjxgz9g
  - &srv_obelix age1hcnc4xp69rwh8dhcvgdrykd45pm9qy6u7cvmda2nrkp934z38gashg8vr8

creation_rules:
  - path_regex: hosts/obelix/secrets.yaml$
    key_groups:
      - age:
        - *srv_obelix
        - *admin_netali
        - *admin_schlagma


