keys:
  - &admin_netali F72925946F580B058FB3F2719C55E636426B40A9
  - &admin_schlagma age1ncc0ukuqyeq8uzcvy2x0cymykrmnhzymgk22kvt7dvz99prjsysqjxgz9g
  - &srv_obelix age1hcnc4xp69rwh8dhcvgdrykd45pm9qy6u7cvmda2nrkp934z38gashg8vr8
  - &srv_miraculix age1j78d0nj0jr7xk5mmgwcepjm7zrj0nun9t8meht3qrq5ywqqqudhs6syp5v

creation_rules:
  - path_regex: hosts/obelix/secrets.yaml$
    key_groups:
      - age:
        - *srv_obelix
        - *admin_schlagma
        pgp:
        - *admin_netali
  - path_regex: hosts/miraculix/secrets.yaml$
    key_groups:
      - age:
        - *srv_miraculix
        - *admin_schlagma
        pgp:
        - *admin_netali

